<div style="text-align:left;">
  <a href="https://code213.tech/" target="_blank">
    <img src="code213.PNG" alt="Code213 Logo" width="200"/>
  </a>
  <p><em>Prepared by Latreche Sara</em></p>
</div>


# 1.0 — Getting Started with TensorFlow
<img src="https://www.tensorflow.org/images/tf_logo_social.png" alt="TensorFlow Logo" width="200"/>

**What is TensorFlow?**  

TensorFlow is an **open-source deep learning framework** developed by Google Brain.  
It is widely adopted in both **academia** and **industry** because:  

- **Flexible computation graphs**: build models dynamically (with eager execution) or statically (with `tf.function`).  
- **GPU/TPU acceleration**: strong hardware support for fast training.  
- **Rich ecosystem**: libraries like TensorFlow Hub, TensorFlow Datasets, TensorFlow Lite, and TensorFlow Probability.  
- **Large community**: tutorials, pretrained models, and active contributions.  

You can think of TensorFlow as both:  
- A **scientific computing library** (similar to NumPy but with GPU/TPU support).  
- A **deep learning framework** (like PyTorch, with high-level Keras API).  



## Table of Contents  

- [1 - Packages](#1)  
- [2 - Outline of the Notebook](#2)  
- [3 - Installing and Importing TensorFlow](#3)  
- [4 - Checking Device (CPU/GPU)](#4)  
- [5 - Creating Tensors](#5)  
  - [5.1 - From Python lists](#5-1)  
  - [5.2 - With built-in functions](#5-2)  
- [6 - Tensor Operations](#6)  
  - [6.1 - Element-wise operations](#6-1)  
  - [6.2 - Dot products](#6-2)  
- [7 - Moving Tensors to GPU](#7)  
- [8 - Exercises](#8)  






## 1 - Packages <a name="1"></a>



In [1]:
# Core packages
import tensorflow as tf
import numpy as np

## 2 - Outline of the Notebook <a name="2"></a>

This notebook covers:  

1. Installing and importing TensorFlow  
2. Checking whether a GPU is available  
3. Creating tensors from Python lists or built-in functions  
4. Performing basic tensor operations  
5. Moving tensors to GPU  
6. Exercises for practice  


## 3 - Installing and Importing TensorFlow <a name="3"></a>


In [ ]:
# Install TensorFlow (uncomment if needed)
# !pip install tensorflow
# Install TensorFlow (uncomment if needed)
# !pip install tensorflow


In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.20.0


## 4 - Checking Device (CPU/GPU) <a name="4"></a>


In [3]:
# List physical devices
tf.config.list_physical_devices()


[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [4]:
# Check for GPU
gpu_available = tf.config.list_physical_devices('GPU')
print("GPU available:", bool(gpu_available))


GPU available: False


## 5 - Creating Tensors <a name="5"></a>


### 5.1 - From Python lists <a name="5-1"></a>


In [5]:
# Create a 1D tensor
tensor_1d = tf.constant([1, 2, 3, 4])
print(tensor_1d)

# Create a 2D tensor
tensor_2d = tf.constant([[1, 2], [3, 4]])
print(tensor_2d)


tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


### 5.2 - With built-in functions <a name="5-2"></a>


In [6]:
# Zeros and ones
zeros = tf.zeros((2,3))
ones = tf.ones((2,3))
print("Zeros:\n", zeros)
print("Ones:\n", ones)

# Random tensors
rand_tensor = tf.random.normal((2,3))
print("Random normal tensor:\n", rand_tensor)


Zeros:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
Ones:
 tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
Random normal tensor:
 tf.Tensor(
[[-0.18062097 -0.04434966  0.32193026]
 [-0.24015346 -0.40053025  0.9347564 ]], shape=(2, 3), dtype=float32)


## 6 - Tensor Operations <a name="6"></a>


### 6.1 - Element-wise operations <a name="6-1"></a>


In [7]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

# Addition
print(a + b)

# Multiplication
print(a * b)


tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


### 6.2 - Dot products <a name="6-2"></a>


In [8]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[5,6],[7,8]])

dot_product = tf.matmul(a,b)
print(dot_product)


tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


## 7 - Moving Tensors to GPU <a name="7"></a>


In [9]:
# Create a tensor on GPU if available
if gpu_available:
    with tf.device('/GPU:0'):
        gpu_tensor = tf.constant([[1.0, 2.0],[3.0, 4.0]])
        print(gpu_tensor.device)


## 8 - Exercises <a name="8"></a>

1. Create a 3x3 tensor of ones and multiply it by 5.  
2. Generate a random 2x4 tensor and compute its sum along axis 1.  
3. Create two 2x2 tensors and compute their dot product.  
4. Check if GPU is available and move a tensor to GPU.
