<div style="text-align:left;">
  <a href="https://code213.tech/" target="_blank">
    <img src="code213.PNG" alt="Code213 Logo" width="200"/>
  </a>
  <p><em>Prepared by Latreche Sara</em></p>
</div>


# 7.0 — Model Implementations
<img src="https://www.tensorflow.org/images/tf_logo_social.png" alt="TensorFlow Logo" width="200"/>

**What is Model Implementation?**  

- Model implementation is the process of **defining, building, and training neural networks**.  
- In this notebook, we will implement:
  - **MLP (Multi-Layer Perceptron)**
  - **CNN (Convolutional Neural Network)**
  - **RNN (Recurrent Neural Network)**  

We will combine **tensors, layers, training loops, and datasets** to create fully functional models.
## Table of Contents  

- [1 - Packages](#1)  
- [2 - Outline of the Notebook](#2)  
- [3 - MLP Implementation](#3)  
- [4 - CNN Implementation](#4)  
- [5 - RNN Implementation](#5)  
- [6 - Exercises](#6)


## 1 - Packages <a name="1"></a>


In [1]:
import tensorflow as tf
from tensorflow.keras import layers, models
import numpy as np


## 2 - Outline of the Notebook <a name="2"></a>

This notebook covers:  

1. Implementing a **Multi-Layer Perceptron** for tabular data  
2. Implementing a **Convolutional Neural Network** for image data  
3. Implementing a **Recurrent Neural Network** for sequential data  
4. Exercises to practice implementing your own models


## 3 - MLP Implementation <a name="3"></a>


In [2]:
# Sample dataset: y = 2x + 1
x_train = np.array([[1.0], [2.0], [3.0], [4.0], [5.0]])
y_train = np.array([[3.0], [5.0], [7.0], [9.0], [11.0]])

# Build MLP model
mlp_model = models.Sequential([
    layers.Dense(8, activation='relu', input_shape=(1,)),
    layers.Dense(4, activation='relu'),
    layers.Dense(1)
])

mlp_model.compile(optimizer='adam', loss='mse')

# Train
mlp_model.fit(x_train, y_train, epochs=50, verbose=0)

# Predictions
predictions = mlp_model.predict(x_train)
print("MLP Predictions:\n", predictions)


c:\Users\MatenTech\AppData\Local\anaconda3\envs\bd\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step
MLP Predictions:
 [[1.4987379]
 [2.7636595]
 [4.02858  ]
 [5.293501 ]
 [6.5584226]]


## 4 - CNN Implementation <a name="4"></a>


In [3]:
# Dummy image data (batch_size=5, height=28, width=28, channels=1)
x_train_img = np.random.rand(5,28,28,1).astype(np.float32)
y_train_img = np.random.randint(0, 2, size=(5,1))

# Build CNN model
cnn_model = models.Sequential([
    layers.Conv2D(16, (3,3), activation='relu', input_shape=(28,28,1)),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(32, (3,3), activation='relu'),
    layers.Flatten(),
    layers.Dense(8, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

cnn_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train
cnn_model.fit(x_train_img, y_train_img, epochs=10, verbose=0)

# Predictions
predictions = cnn_model.predict(x_train_img)
print("CNN Predictions:\n", predictions)


c:\Users\MatenTech\AppData\Local\anaconda3\envs\bd\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step
CNN Predictions:
 [[0.41242522]
 [0.32982832]
 [0.32450855]
 [0.41128102]
 [0.34680754]]


## 5 - RNN Implementation <a name="5"></a>


In [4]:
# Dummy sequential data: batch_size=5, timesteps=3, features=1
x_seq = np.array([[[1],[2],[3]], [[2],[3],[4]], [[3],[4],[5]], [[4],[5],[6]], [[5],[6],[7]]], dtype=np.float32)
y_seq = np.array([[6],[9],[12],[15],[18]], dtype=np.float32)

# Build RNN model
rnn_model = models.Sequential([
    layers.SimpleRNN(8, activation='relu', input_shape=(3,1)),
    layers.Dense(1)
])

rnn_model.compile(optimizer='adam', loss='mse')

# Train
rnn_model.fit(x_seq, y_seq, epochs=50, verbose=0)

# Predictions
predictions = rnn_model.predict(x_seq)
print("RNN Predictions:\n", predictions)


c:\Users\MatenTech\AppData\Local\anaconda3\envs\bd\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 360ms/step
RNN Predictions:
 [[-0.7644332]
 [-1.0378869]
 [-1.3113406]
 [-1.5847945]
 [-1.8582482]]


## 6 - Exercises <a name="6"></a>

1. Build an MLP model with 3 hidden layers of sizes 16, 8, 4 to learn y = 3x + 2.  
2. Create a CNN for MNIST-like images (28x28x1) with 2 Conv2D layers and train on dummy data.  
3. Implement an RNN using GRU for a sequence prediction problem.  
4. Experiment with different activation functions in MLP, CNN, and RNN models.  
5. Combine CNN + RNN for sequence of images (optional challenge).
