<div style="text-align:left;">
  <a href="https://code213.tech/" target="_blank">
    <img src="../code213.PNG" alt="code213">
  </a>
  <p><em>prepared by Latreche Sara</em></p>
</div>

# 1.0 — Getting Started with PyTorch
<img src="https://pytorch.org/assets/images/pytorch-logo.png" alt="PyTorch Logo" width="200"/>

**What is PyTorch?**  

PyTorch is an **open-source deep learning framework** developed by Facebook’s AI Research (FAIR) lab.  
It is widely adopted in both **academia** and **industry** because:  

-  **Dynamic graphs**: easy to debug and experiment with.  
-  **GPU acceleration**: strong CUDA support for fast training.  
-  **Rich ecosystem**: libraries like TorchVision, TorchText, and TorchAudio.  
-  **Large community**: tutorials, pretrained models, and active contributions.  

 You can think of PyTorch as both:  
- A **scientific computing library** (similar to NumPy but with GPU support).  
- A **deep learning framework** (like TensorFlow, but often considered more intuitive).  




## Table of Contents  

- [1 - Packages](#1)  
- [2 - Outline of the Notebook](#2)  
- [3 - Installing and Importing PyTorch](#3)  
- [4 - Checking Device (CPU/GPU)](#4)  
- [5 - Creating Tensors](#5)  
  - [5.1 - From Python lists](#5-1)  
  - [5.2 - With built-in functions](#5-2)  
- [6 - Tensor Operations](#6)  
  - [6.1 - Element-wise operations](#6-1)  
  - [6.2 - Dot products](#6-2)  
- [7 - Moving Tensors to GPU](#7)  
- [8 - Exercises](#8)  




<a name='1'></a>
## 1 - Packages


In [2]:
import torch  

# Numerical operations
import numpy as np  

# PyTorch ecosystem libraries
import torchvision
import torchaudio

# For plotting (optional, but useful for visualization)
import matplotlib.pyplot as plt

# Check versions
print("Torch version:", torch.__version__)
print("TorchVision version:", torchvision.__version__)
print("TorchAudio version:", torchaudio.__version__)

Torch version: 2.8.0+cpu
TorchVision version: 0.23.0+cpu
TorchAudio version: 2.8.0+cpu


<a name='2'></a>
## 2 - Outline of the Notebook


<a name='3'></a>
## 3 - Installing and Importing PyTorch
PyTorch is an open-source deep learning framework developed by Facebook's AI Research lab.  
It provides a flexible platform for building and training neural networks.  

### Installation  

To install PyTorch using `pip`, open your terminal and run:  

```bash
pip install torch


<a name='6'></a>
## 6 - Exercises  

1. Modify the decay schedule: make $\epsilon$ decrease **slower** or **faster**.  
2. Try a **larger grid size** for the snake. What changes?  
3. Fix $\epsilon=1.0$ (always random). What happens to the score trend?  
4. Fix $\epsilon=0.0$ (always exploit). Why does the agent fail?  
5. Add a new reward: -1 per move. Does the agent play differently?  


<a name='4'></a>
## 4 - Checking Device (CPU/GPU)  

PyTorch can run computations on both **CPU** and **GPU (CUDA-enabled)** devices.  
By default, tensors are created on the CPU, but if you have a GPU available, you can accelerate training significantly.  

We can check which device is available using the following commands:
## 4 - Checking Device (CPU/GPU)  

Before we check for device availability in PyTorch, let’s briefly review the types of processors used in deep learning:  
![CPU vs GPU vs TPU](../859760b6-1dbd-4a9c-a478-91739ba5ef6b.png)
- **CPU (Central Processing Unit):**  
  - The "brain" of the computer.  
  - Optimized for **sequential tasks** and general-purpose computing.  
  - Great for running operating systems, applications, and handling logic-intensive tasks.  

- **GPU (Graphics Processing Unit):**  
  - Originally designed for rendering graphics in games.  
  - Contains thousands of smaller cores designed for **parallel processing**.  
  - Ideal for deep learning because matrix multiplications and tensor operations can be parallelized.  
  - This massively speeds up training compared to CPUs.  

- **TPU (Tensor Processing Unit):**  
  - Developed by **Google**.  
  - Specialized hardware optimized specifically for deep learning and tensor computations.  
  - Available on **Google Cloud Platform**.  

### Why does a GPU accelerate training?  
Deep learning requires performing millions (or even billions) of matrix multiplications and tensor operations.  
- On a **CPU**, these operations are executed mostly **sequentially**.  
- On a **GPU**, thousands of cores perform these operations **in parallel**, making training much faster.  
- **TPUs** take this further by being custom-built for tensor math, which is the core of deep learning.  



In [3]:

# Check if CUDA (NVIDIA GPU) is available
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("GPU is available. Using:", torch.cuda.get_device_name(0))
else:
    device = torch.device("cpu")
    print("GPU not available. Using CPU.")


GPU not available. Using CPU.


<a name='5'></a>
## 5 - Creating Tensors  
<a name='5'></a>
## 5 – Creating Tensors  

A **tensor** is the fundamental **data structure of PyTorch**.  
It is an N-dimensional array used to store data, perform computations, and hold model parameters.  

- **0-D Tensor (Scalar):** A single number (e.g., `7`).  
- **1-D Tensor (Vector):** A list of numbers (e.g., `[1, 2, 3]`).  
- **2-D Tensor (Matrix):** A table/grid of numbers (e.g., `[[1, 2], [3, 4]]`).  
- **N-D Tensor:** Higher-order structures (e.g., batches of images, videos, multi-channel signals).  

### Visual: Scalars → Vectors → Matrices → Higher-Dimensional Tensors  

![Tensors diagram](../tensor.png)

### Why Tensors in PyTorch?
- Similar to **NumPy arrays**, but optimized for GPU usage.  
- Enable **automatic differentiation**, which is crucial for training deep learning models.  




<a name='5-1'></a>
### 5.1 - From Python lists  

In [ ]:
# ### 5.1 - From Python lists
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print("Tensor from list:\n", x_data)

# From NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print("Tensor from NumPy array:\n", x_np)

<a name='5-2'></a>
### 5.2 - With built-in functions  

In [4]:
# ### 5.2 - With built-in functions
shape = (2, 3,)
rand_tensor = torch.rand(shape)   # random values
ones_tensor = torch.ones(shape)   # all ones
zeros_tensor = torch.zeros(shape) # all zeros

print("Random Tensor:\n", rand_tensor)
print("Ones Tensor:\n", ones_tensor)
print("Zeros Tensor:\n", zeros_tensor)


Random Tensor:
 tensor([[0.3051, 0.2705, 0.8734],
        [0.6569, 0.4967, 0.7114]])
Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


<a name='6'></a>
## 6 - Tensor Operations 

<a name='6-1'></a>
### 6.1 - Element-wise operations  


In [5]:
# ## 6 - Tensor Operations

# ### 6.1 - Element-wise operations
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
print("Example tensor:\n", tensor)

# Element-wise multiplication
print("Element-wise multiplication:\n", tensor * tensor)

# In-place addition
tensor.add_(5)
print("After in-place addition (+5):\n", tensor)


Example tensor:
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
Element-wise multiplication:
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
After in-place addition (+5):
 tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


<a name='6-2'></a>
### 6.2 - Dot products  

In [6]:
# ### 6.2 - Dot products
# Matrix multiplication
result1 = tensor.matmul(tensor.T)
result2 = tensor @ tensor.T   # shorthand
print("Matrix multiplication (matmul):\n", result1)
print("Matrix multiplication (@):\n", result2)


Matrix multiplication (matmul):
 tensor([[133., 133., 133., 133.],
        [133., 133., 133., 133.],
        [133., 133., 133., 133.],
        [133., 133., 133., 133.]])
Matrix multiplication (@):
 tensor([[133., 133., 133., 133.],
        [133., 133., 133., 133.],
        [133., 133., 133., 133.],
        [133., 133., 133., 133.]])


<a name='7'></a>
## 7 - Moving Tensors to GPU  

In [7]:
if torch.cuda.is_available():
    gpu_tensor = tensor.to("cuda")
    print("Tensor moved to GPU:", gpu_tensor.device)
else:
    print("No GPU found, running on CPU")

No GPU found, running on CPU


<a name='8'></a>
## 8 - Exercises 